  (function () {
    if (new URLSearchParams(location.search).has('embed')) {
      document.documentElement.classList.add('is-embed');
    }
    const TOTAL = 45000;
    const CAPTIONS = [
      { at: 0, text: 'Brittle test scripts fail every time your UI changes.' },
      { at: 5000, text: 'Our GenAI engine generates robust Playwright suites from real app state.' },
      { at: 15000, text: 'Self-heal in real time — <em>role → text → CSS</em>. Zero pipeline downtime.' },
      { at: 30000, text: 'Instant Proof Artifacts — root cause, severity, suggested fix.' },
      { at: 40000, text: 'CertusQA — <em>Certainty, Verified.</em>' },
    ];

    const SPEC_LINES = [
      { html: `<span class="cm">// Autogenerated · CertusQA engine adapters</span>\n` },
      { html: `<span class="kw">const</span> { SmartLocatorEngine } = <span class="fn">require</span>(<span class="str">'certusqa/core'</span>);\n` },
      { html: `<span class="kw">const</span> { generateTriageReport } = <span class="fn">require</span>(<span class="str">'certusqa/core'</span>);\n\n` },
      { html: `<span class="fn">test</span>(<span class="str">'Pass 2: Proactive Self-Healing'</span>, <span class="kw">async</span> ({ page }) => {\n` },
      { html: `  <span class="kw">const</span> engine = <span class="kw">new</span> <span class="hi">SmartLocatorEngine</span>(page);\n` },
      { html: `  <span class="kw">const</span> result = <span class="kw">await</span> engine.<span class="hi">smartClick</span>({\n` },
      { html: `    originalSelector: <span class="str">'#checkout-submit-btn'</span>,\n` },
      { html: `    fallbackText: <span class="str">'Place Secure Order'</span>,\n` },
      { html: `    context: <span class="str">'Main checkout submission'</span>,\n` },
      { html: `  });\n` },
      { html: `  expect(result.healed).<span class="fn">toBe</span>(<span class="kw">true</span>);\n` },
      { html: `});` },
    ];

    const PROOF_HTML = `<span class="k">"</span><span class="k">schemaVersion</span><span class="k">"</span>: <span class="s">"1.0.0"</span>,
<span class="k">"</span><span class="k">classification</span><span class="k">"</span>: {
<span class="flash"><span class="k">"category"</span>: <span class="s">"SELECTOR_HEALED"</span>,
<span class="k">"severity"</span>: <span class="s">"INFO"</span>,
<span class="k">"outcome"</span>: <span class="s">"HEALED"</span></span>
},
<span class="k">"</span><span class="k">remediation</span><span class="k">"</span>: {
<span class="k">"ownerHint"</span>: <span class="s">"test-inventory"</span>,
<span class="k">"confidence"</span>: <span class="s">"high"</span>,
<span class="flash"><span class="k">"suggestedCodeFix"</span>: <span class="s">"Prefer role+name…"</span></span>
},
<span class="k">"</span><span class="k">evidence</span><span class="k">"</span>: {
<span class="k">"locator"</span>: {
  <span class="k">"originalSelector"</span>: <span class="s">"#checkout-submit-btn"</span>,
  <span class="k">"healedStrategy"</span>: <span class="s">"role-name-fallback"</span>
}
}`;

    const els = {
      scenes: [...document.querySelectorAll('.scene')],
      caption: document.getElementById('caption'),
      progress: document.getElementById('progressFill'),
      scrub: document.getElementById('scrub'),
      time: document.getElementById('timeReadout'),
      play: document.getElementById('btnPlay'),
      replay: document.getElementById('btnReplay'),
      dots: [...document.querySelectorAll('#sceneDots button')],
      termLines: [...document.querySelectorAll('#termBody .line')],
      nodeTest: document.getElementById('nodeTest'),
      nodeDeploy: document.getElementById('nodeDeploy'),
      scanChip: document.getElementById('scanChip'),
      genBadge: document.getElementById('genBadge'),
      editor: document.getElementById('editorBody'),
      ladderSteps: [...document.querySelectorAll('#ladder .step')],
      domBtn: document.getElementById('domBtn'),
      domId: document.getElementById('domId'),
      healToast: document.getElementById('healToast'),
      healPipe: document.getElementById('healPipeTest'),
      proofJson: document.getElementById('proofJson'),
      jiraChip: document.getElementById('jiraChip'),
      fixBox: document.getElementById('fixBox'),
      ctaBtn: document.getElementById('ctaBtn'),
    };

    els.proofJson.innerHTML = PROOF_HTML;

    let t = 0;
    let playing = true;
    let lastTs = null;
    let reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    function sceneIndex(ms) {
      if (ms < 5000) return 0;
      if (ms < 15000) return 1;
      if (ms < 30000) return 2;
      if (ms < 40000) return 3;
      return 4;
    }

    function fmt(ms) {
      const s = Math.min(TOTAL, Math.max(0, ms));
      const sec = Math.floor(s / 1000);
      return `0:${String(sec).padStart(2, '0')} / 0:45`;
    }

    function setCaption(ms) {
      let text = CAPTIONS[0].text;
      for (const c of CAPTIONS) {
        if (ms >= c.at) text = c.text;
      }
      if (els.caption.innerHTML !== text) els.caption.innerHTML = text;
    }

    function activateScene(idx) {
      els.scenes.forEach((sc, i) => {
        const on = i === idx;
        sc.classList.toggle('is-active', on);
        sc.setAttribute('aria-hidden', on ? 'false' : 'true');
      });
      els.dots.forEach((d, i) => d.classList.toggle('is-on', i === idx));
    }

    /* Scene-local resets + progressive reveals keyed to absolute timeline */
    function render(ms) {
      const idx = sceneIndex(ms);
      activateScene(idx);
      setCaption(ms);
      els.progress.style.width = `${(ms / TOTAL) * 100}%`;
      els.scrub.value = String(Math.floor(ms));
      els.time.textContent = fmt(ms);

      /* Scene 1 local (0–5000) */
      const s1 = ms;
      els.termLines.forEach((line) => {
        const at = Number(line.dataset.t);
        line.classList.toggle('show', s1 >= at || reduced);
      });
      if (s1 >= 3500) {
        els.nodeTest.classList.remove('is-run');
        els.nodeTest.classList.add('is-fail');
        els.nodeDeploy.classList.add('is-blocked');
      } else if (s1 >= 500) {
        els.nodeTest.classList.add('is-run');
        els.nodeTest.classList.remove('is-fail');
        els.nodeDeploy.classList.remove('is-blocked');
      } else {
        els.nodeTest.classList.remove('is-run', 'is-fail');
        els.nodeDeploy.classList.remove('is-blocked');
      }

      /* Scene 2 local (5000–15000) */
      const s2 = ms - 5000;
      if (idx === 1 || (ms >= 5000 && ms < 15000)) {
        els.scanChip.classList.toggle('show', s2 >= 400 || reduced);
        const linesToShow = reduced
          ? SPEC_LINES.length
          : Math.min(SPEC_LINES.length, Math.max(0, Math.floor((s2 - 800) / 550) + 1));
        els.editor.innerHTML = SPEC_LINES.slice(0, Math.max(0, linesToShow)).map((l) => l.html).join('');
        els.genBadge.classList.toggle('show', linesToShow >= SPEC_LINES.length || reduced);
      }

      /* Scene 3 local (15000–30000) */
      const s3 = ms - 15000;
      els.ladderSteps.forEach((step) => {
        step.classList.remove('is-active', 'is-miss', 'is-hit', 'is-skip');
        const st = step.querySelector('.step-status');
        const ico = step.querySelector('.step-ico');
        st.textContent = '—';
        ico.textContent = String(Number(step.dataset.step) + 1);
      });
      els.domBtn.classList.remove('is-target');
      els.domId.textContent = 'id="#btn-x7k2" · primary miss';
      els.healToast.classList.remove('show');
      els.healPipe.classList.remove('is-ok');
      els.healPipe.classList.remove('is-fail');

      if (ms >= 15000 && ms < 30000) {
        // step 0 miss @ 2s
        if (s3 >= 2000) {
          const s0 = els.ladderSteps[0];
          s0.classList.add('is-miss');
          s0.querySelector('.step-status').textContent = 'miss';
          s0.querySelector('.step-ico').textContent = '✕';
        } else if (s3 >= 800) {
          els.ladderSteps[0].classList.add('is-active');
          els.ladderSteps[0].querySelector('.step-status').textContent = 'try';
        }
        // step 1 hit @ 5s
        if (s3 >= 5500) {
          const s1s = els.ladderSteps[1];
          s1s.classList.add('is-hit');
          s1s.querySelector('.step-status').textContent = 'hit';
          s1s.querySelector('.step-ico').textContent = '✓';
          els.domBtn.classList.add('is-target');
          els.domId.textContent = "role=button · name='Place Secure Order'";
          els.healToast.classList.add('show');
          els.ladderSteps[2].classList.add('is-skip');
          els.ladderSteps[3].classList.add('is-skip');
          els.ladderSteps[2].querySelector('.step-status').textContent = 'skip';
          els.ladderSteps[3].querySelector('.step-status').textContent = 'skip';
        } else if (s3 >= 3500) {
          els.ladderSteps[1].classList.add('is-active');
          els.ladderSteps[1].querySelector('.step-status').textContent = 'try';
        }
        if (s3 >= 9000) {
          els.healPipe.classList.add('is-ok');
          els.healPipe.textContent = 'Test ✓';
        }
      }

      /* Scene 4 */
      if (ms >= 30000 && ms < 40000) {
        const s4 = ms - 30000;
        els.fixBox.classList.toggle('show', s4 >= 2500 || reduced);
        els.jiraChip.classList.toggle('show', s4 >= 4500 || reduced);
      } else {
        els.fixBox.classList.remove('show');
        els.jiraChip.classList.remove('show');
      }

      /* Scene 5 */
      els.ctaBtn.classList.toggle('show', ms >= 42000 || (reduced && ms >= 40000));
    }

    function tick(ts) {
      if (lastTs == null) lastTs = ts;
      const dt = ts - lastTs;
      lastTs = ts;
      if (playing) {
        t += dt;
        if (t >= TOTAL) {
          t = TOTAL;
          playing = false;
          els.play.textContent = 'Play';
          els.play.setAttribute('aria-pressed', 'false');
        }
        render(t);
      }
      requestAnimationFrame(tick);
    }

    function seek(ms) {
      t = Math.max(0, Math.min(TOTAL, ms));
      lastTs = null;
      render(t);
    }

    els.play.addEventListener('click', () => {
      if (t >= TOTAL) seek(0);
      playing = !playing;
      els.play.textContent = playing ? 'Pause' : 'Play';
      els.play.setAttribute('aria-pressed', playing ? 'true' : 'false');
      lastTs = null;
    });

    els.replay.addEventListener('click', () => {
      seek(0);
      playing = true;
      els.play.textContent = 'Pause';
      els.play.setAttribute('aria-pressed', 'true');
    });

    els.scrub.addEventListener('input', () => {
      playing = false;
      els.play.textContent = 'Play';
      els.play.setAttribute('aria-pressed', 'false');
      seek(Number(els.scrub.value));
    });

    els.dots.forEach((btn) => {
      btn.addEventListener('click', () => {
        seek(Number(btn.dataset.jump));
        playing = true;
        els.play.textContent = 'Pause';
        els.play.setAttribute('aria-pressed', 'true');
        lastTs = null;
      });
    });

    window.addEventListener('keydown', (e) => {
      if (
        e.code === 'Space' &&
        (e.target === document.body || e.target === document.documentElement)
      ) {
        e.preventDefault();
        els.play.click();
      }
    });

    render(0);
    requestAnimationFrame(tick);
  })();
